### ISSUE TITLE
Decidere se e come fare (a che livello) dead code elimination. 

### ISSUE THREAD

**Issue by herrBez** [StefanoMunari/FAC#11]
Decidere se e come fare (a che livello) dead code elimination. 

Quella molto semplice if(false) BLOCCO ---> codice vuoto ecc.

**Comment by herrBez** [comment]
maybe it is beyond the scope of the project. Waiting for a feedback

**Comment by StefanoMunari** [comment]
Out of scope for me. KISS :-)
Can we close it?
