### ISSUE TITLE
IMPROVE ERROR REPORTING

### ISSUE THREAD

**Issue by herrBez** [StefanoMunari/FAC#13]
Improve type checker error reporting especially with respect to b0 == b1 e b0 <> b1

**Comment by herrBez** [comment]
In general we should try to improve error reporitng

**Comment by herrBez** [comment]
In general we should improve error reporting so that it is easier to detect where the error happen!

**Comment by StefanoMunari** [comment]
Maybe we could use a "scope-style" approach. 
For example, if the error occurs in symbol_table.installID 
`yyerror("symbol_table::installID - The id %s is already installed", id);`

**Comment by herrBez** [comment]
Nice idea. I will try to implement it :)

**Comment by herrBez** [comment]
An Idea:
We could add to the header of `yyerror` a boolean that says if the exact line is known. If it is the case then we do not print the "Around Line xy". If you give me the OK, i will try to fix it

**Comment by StefanoMunari** [comment]
Sorry. I do not agree on the boolean parameter.

**Comment by herrBez** [comment]
Ok.
