### ISSUE TITLE
Controllare che sia effettivamente corretto il printing C finale (--> testare doppi cicli annidati)

### ISSUE THREAD

**Issue by herrBez** [StefanoMunari/FAC#2]
Controllare che sia effettivamente corretto il printing C finale (--> testare doppi cicli annidati)

**Comment by StefanoMunari** [comment]
Probably the best way to test any printed result is to run the printed code in C (for C printer). Thus, it is fairly important to complete the printer first.

**Comment by StefanoMunari** [comment]
The idea is to use the "printers" as code generators. At the end of the project, the printers will be useless if they will not generate code. I'm creating a new branch for this refactoring.
