### ISSUE TITLE
Segmentation Fault possibly due to wrong path

### ISSUE THREAD

**Issue by herrBez** [StefanoMunari/FAC#21]
Segmentation Fault recipe:

Go in "result" directory.
Execute an exercise `../bin/fac ../examples/ex1.f C`

**Comment by StefanoMunari** [comment]
I wrote a procedure which computes the correct directory even if fac is executed from its subdirs. It warns with an error message if fac is executed outside the project's dir. 
However, I strongly suggest to use 
`make run ARGS="examples/exname.f C" to run fac`
