### ISSUE TITLE
Suppress some outputs or use options to limitate it

### ISSUE THREAD

**Issue by herrBez** [StefanoMunari/FAC#24]
We could add the option `verbose` to improve readability of output.
For instance the printing of the ast tree should be optional. Waiting for a feedback..

**Comment by StefanoMunari** [comment]
Ok. good idea. maybe naming the option `AST` instead of `verbose`?

**Comment by herrBez** [comment]
Maybe we could add an option verbose that explains ALL passages, but not sure if it suites u

**Comment by herrBez** [comment]
This issue is done.
