### ISSUE TITLE
Sistemare makefile in modo tale da creare la cartella bin non all'interno di src

### ISSUE THREAD

**Issue by herrBez** [StefanoMunari/FAC#6]
Sistemare makefile in modo tale da creare la cartella bin non all'interno di src

**Comment by StefanoMunari** [comment]
1. move makefile in root dir
2. tidy-up c_src : enforce "simil-package" tree structure - related to #5
3. move bin/ + obj/ in root dir
4. add _run_ command to makefile (to run the FAC binary)
5. add _profile_ command to makefile (for valgrind memory debugger and profiler)
6. add _example_ command to makefile (to exec all the examples)
7. add PRINTER flag to makefile (use it as argv input for FAC)
8. add VGOPTS flag to makefile (use it to set valgrind options when _profile_ is executed)

**Comment by StefanoMunari** [comment]
# TODO
6. add example command to makefile (to exec all the examples) => need all the examples fixed
7. add PRINTER flag to makefile (use it as argv input for FAC) => need a switch to choose the printer in parser.y

**Comment by herrBez** [comment]
6. Prerequisistes done. (At least the `examples/ex*.f`)
