### ISSUE TITLE
Aggiungere a livello sintattico il controllo che i blocchi di if ed else non siano vuoti

### ISSUE THREAD

**Issue by herrBez** [StefanoMunari/FAC#8]
Aggiungere a livello sintattico il controllo che i blocchi di if ed else non siano vuoti

**Comment by herrBez** [comment]
Maybe it is better to do it in the type checker. Waiting for a feedback :)

**Comment by StefanoMunari** [comment]
Fail-fast principle. This implies to check the IF "structure" in lexer using the lookahead operator. Very simple.
